name = "offerlayer"
client_id = ""
application_url = "https://api.offerlayer.io"
embedded = true

[access_scopes]
scopes = "read_products,read_orders,write_discounts"

[auth]
redirect_urls = [ "https://api.offerlayer.io/auth/callback" ]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid", "orders/cancelled", "refunds/create" ]
  uri = "https://api.offerlayer.io/v1/webhooks/shopify"
