name = "offerlayer"
client_id = ""
application_url = "https://offerlayer.grok.me"
embedded = true

[access_scopes]
scopes = "read_products,read_orders,write_orders,read_customers"

[auth]
redirect_urls = [ "https://offerlayer.grok.me/auth/callback" ]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid", "orders/cancelled", "refunds/create" ]
  uri = "https://offerlayer.grok.me/v1/webhooks/shopify"
